youtube_targets:
  # Format is "{org}:{channelID}:{topics}" (all are case sensitive)
  # You can try your thing by filling them into the following url template

  # https://holodex.net/api/v2/live?org=<org>&channel_id=<channelID>&topic=<one of your topics>

  # Org can be left out most of the time, but is useful for if you want to download all topics from an orginization(see 3rd example)
  # A comprehensive list of all topics can be found here: https://docs.google.com/spreadsheets/d/1molZTK_krbT28ksljthRFiUDDiGP8TsXVh4j7m2Q3S4/edit#gid=1285117812
  # Examples:
  # Download all talk and morning streams from Laplus
  - "Hololive:UCENwRMx5Yh42zWpzURebzTw:talk,morning"
  # Download all streams from Roboco
  - "Hololive:UCENwRMx5Yh42zWpzURebzTw:*"
  # Download all ASMR streams from Nijisanji
  - "Nijisanji:*:asmr"
  # Download all streams from Ina Ninomae ignoring org and topics
  - "*:UCMwGHR0BTZuLsmjY_NT5Pwg:*"



locations:
  # Final folder template to use for the downloaded stuff
  # Variables:
  #   $channel_id - The channel name
  #   $channel_name - The channel name
  #   $channel_org - The organization that the channel belongs to(will be twitter for twitter)
  #   $id - The video/tweet ID
  #   $title - The title of the target(will be same as $channel for twitter)
  #   $ext - The file extension
  #   $topic - The topic name
  #   $date - The date of the target in format YYYYMMDD
  final: /downloads/$channel_id/[$date] $title.$ext
